test:
	go test ./future/... ./margin/... ./spot/... ./logging/...

cover:
	go test -cover ./futures/... ./margin/... ./spot/... ./logging/...

trace:
	go test -race ./future/... ./margin/... ./spot/... ./logging/...